title: "LAAC test"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
search_enabled: true

#description: Handbook for the LAAC team

#open links in a new tab
#aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

#bottom of page
footer_content: "Language acquisition across cultures team, LSCP. DEC ENS Paris, PSL university"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

compress_html:
  ignore:
    envs: all
